Revalidate authorization requirement on evidence harvester
data-altinn-no/core pull request #2
Opened 2022-08-25 11:35 UTC by nlundee

2022-08-25 12:57 UTC, elsand requested changes

2022-08-25 13:26 UTC, nlundee commented on Dan.Core/FuncEvidenceHarvester.cs
> +        private static IEnumerable<string> GetQueryParamsToSkip()
✔

2022-08-26 06:22 UTC, elsand requested changes
Ser bra ut :) Bare et par småting du fikser kjapt.

2022-08-26 06:22 UTC, elsand commented on Dan.Core/Services/AuthorizationRequestValidatorService.cs
> +            foreach (var requirement in requirements.Values.ToArray())
Pirk: ToArray() kan du droppe her, det medfører bare en unødvendig allokering.

2022-08-26 06:22 UTC, elsand commented on Dan.Common/Models/AuthorizationRequest.cs
> +    [DataMember(Name = "fromEvidenceHarvester")]
Pirk: Fint om du legger inn en kjapp kommentar tilsvarende de andre propertyene.

2022-08-30 07:37 UTC, elsand approved these changes

2022-08-30 08:27 UTC, merged